import {
  Cross,
  Orbit,
  Syringe,
  BrushCleaning,
  HandHeart,
  TrendingUpDownIcon,
} from "lucide-react";

import peritoneal_dialysis_img_1 from "@/assets/images/peritoneal_dialysis_1.png";
import peritoneal_dialysis_img_2 from "@/assets/images/peritoneal_dialysis_2.png";
import basic_care_img from "@/assets/images/basic_care2.png";
import treatment_care_img from "@/assets/images/treatment_care2.png";
import domestic_care_img from "@/assets/images/domestic_care2.png";
import respite_care_man_img from "@/assets/images/respite_care_man2.png";
import respite_care_woman_img from "@/assets/images/respite_care_woman2.png";
import other_services_img_1 from "@/assets/images/other_services_img_12.png";
import other_services_img_2 from "@/assets/images/other_services_img_22.png";

// const data = {
//   leistungen: {
//     id: 1,
//     label: "Our Services",
//     title: "Home care - because home is where the heart is",
//     description: [
//       "SemiCare follows a special concept: We offer the same leistungen as any other care service.",
//       "We offer professional leistungen covered by health insurance. In addition, you can also book medical and non-medical leistungen that are not reimbursable, if desired. The advantage: You can choose the leistungen that you need and want, and we will take care of the rest. ",
//       "We organize the necessary help in a compact and tailored way, without having to find a multitude of helpers. Which leistungen are covered by health insurance?",
//       "We will clarify which leistungen you will have to pay for yourself and what that will cost in a non- binding consultation before the contract is concluded.",
//     ],
//
//     leistungen: [
//       {
//         id: 1,
//         title: "Peritoneal Dialysis (CAPD)",
//         icon: Cross,
//         url: "/leistungen/peritoneal-dialysis",
//         slug: "peritoneal-dialysis",
//         description: [
//           "Peritoneal dialysis changes everyday life – for patients as well as their families. It brings with it many questions, uncertainties, and anxieties. At SemiCare, we won't leave you alone with these challenges. We provide competent, empathetic, and reliable support to people undergoing peritoneal dialysis – right in your own home. We explain each step clearly, so you can feel confident.",
//           "Peritoneal dialysis is a kidney replacement therapy used to remove toxins and excess water from the blood in patients with chronic kidney failure. Unlike hemodialysis, this process takes place inside the body, utilizing the body's own peritoneum (the lining of the abdominal cavity) as a filter.",
//           'A special dialysis solution is introduced via a catheter permanently implanted in the abdominal cavity. The peritoneum acts as a "semi-permeable" membrane through which waste products from the blood pass into the solution.',
//           "Our leistungen include the following:",
//         ],
//         serviceList: [
//           "Professional support for peritoneal dialysis (CAPD) at home Environment",
//           "Implementation and monitoring of CAPD and APD (cycler) according to medical advice arrangement",
//           "Exit - Change of association",
//           "Assistance with ordering materials (Baxter or Fresenius)",
//           "Strict adherence to hygiene standards for infection prevention - Preparation, connection and conclusion of dialysis",
//           "Control of the inflow and outflow volume",
//           "Observation and documentation of general condition",
//           "Early detection and forwarding of abnormalities",
//           "Guidance and support for patients and their families",
//           "Close cooperation with doctors and dialysis centers",
//           "Relief for family members through reliable, trained and structured care",
//         ],
//         images: [peritoneal_dialysis_img_1, peritoneal_dialysis_img_2],
//       },
//
//       {
//         id: 2,
//         title: "Basic care",
//         icon: Orbit,
//         url: "/leistungen/basic-care",
//         slug: "basic-care",
//         description: [
//           "Basic care supports people with their daily needs and ensures well-being, hygiene, and safety. The goal of basic care is to maintain independence as much as possible, promote health, and enable people to live with dignity. Our team offers the following basic care leistungen:",
//           "Basic care is particularly important to prevent infections.",
//         ],
//         serviceList: [
//           "Showering, bathing, washing - Help with dressing and undressing",
//           "Cooking, preparing food in bite-sized portions",
//           "Assistance with eating",
//           "Administration of tube feeding and oral nutritional supplements",
//           "Assistance with using the toilet",
//           "Use of incontinence products",
//           "Cleaning of urethral catheter, changing of the catheter bag",
//           "Cleaning and care of artificial exits",
//           "Nursing measures to prevent contractures, pneumonia, Oral thrush, pressure sores, thrombosis and constipation",
//           "Storage with storage aids",
//           "Support while walking",
//           "Transfer, e.g., from bed to wheelchair",
//           "Activating care with movement exercises",
//         ],
//         images: [basic_care_img],
//       },
//       {
//         id: 3,
//         title: "Treatment care",
//         icon: Syringe,
//         url: "/leistungen/treatment-care",
//         slug: "treatment-care",
//         description: [
//           "Treatment care encompasses medical measures carried out by nursing professionals in the home environment on the orders of a physician to cure, alleviate, or prevent the worsening of illnesses. It falls under the umbrella of home-based nursing care (German Social Code, Book V) and is regulated by the [relevant authority/organization].",
//           "Health insurance covers the costs, regardless of the care level classification. This includes all activities that are to be carried out by healthcare and elderly care professionals based on a doctor's prescription, such as...",
//         ],
//         serviceList: [
//           "Administering injections (e.g., insulin or thrombosis prophylaxis)",
//           "Wound care and dressing changes",
//           "Setting up medication and preparing for medication administration",
//           "Pressure ulcer treatment",
//           "Measurement of vital signs, blood sugar and weight control",
//           "Putting on and taking off compression stockings, applying Compression bandages",
//           "Stoma care",
//         ],
//         images: [treatment_care_img],
//       },
//       {
//         id: 4,
//         title: "Domestic leistungen",
//         icon: BrushCleaning,
//         url: "/leistungen/domestic-leistungen",
//         slug: "domestic-leistungen",
//         description: [
//           "In addition, we offer various supplementary leistungen that are not part of basic and medical care. If needed, our patients can book domestic support leistungen to facilitate daily life. These are billed either as in-kind benefits through the long- term care insurance or as private leistungen.",
//           "Domestic leistungen support individuals in managing their household tasks and daily chores. These leistungen are designed to help maintain a clean, organized, and comfortable living environment, especially for those who may have difficulty performing these tasks themselves due to age, illness, or disability. Our domestic leistungen include:",
//         ],
//         serviceList: [
//           "Grocery shopping and errands",
//           "Cleaning and tidying up the living space",
//           "Meal preparation and cooking",
//           "Wash the dishes and clean the kitchen",
//           "Laundry and ironing",
//           "Assistance with organizing household items",
//           "Light maintenance tasks around the home, eg., changing light bulbs, minor repairs",
//         ],
//         images: [domestic_care_img],
//       },
//       {
//         id: 5,
//         title: "Respite care",
//         icon: HandHeart,
//         url: "/leistungen/respite-care",
//         slug: "respite-care",
//         description: [
//           "Respite care provides temporary relief for primary caregivers, allowing them to take a break from their caregiving responsibilities. This service is designed to support caregivers who may be experiencing burnout or need time to attend to their own needs while ensuring that their loved ones continue to receive quality care.",
//           "You want to go on vacation. You are ill or simply at the end of your rope. You do not have energy. But then there's that one person you lovingly care for every day. And you wonder: Who will look after them when I can't? Respite care exists precisely for these moments.",
//           "Caregiving is love, responsibility, and often also physical and emotional strain. You do amazing work – every single day. If you want to travel, need to rest, or are ill yourself, we will take over the care of your loved one during this time – reliably, respectfully, and with heart.",
//           "Respite care can be arranged for a few hours, a day, or even longer periods, depending on the needs of the caregiver and the care recipient. During respite care, trained professionals or volunteers step in to provide care and support to the individual in need, allowing the primary caregiver to rest, recharge, or attend to other responsibilities.",
//           "You can let go – without a guilty conscience.",
//           "Our caregivers help with everything that is needed:",
//         ],
//         serviceList: [
//           "Get up, wash and get dressed",
//           "Personal care and hygiene assistance",
//           "Medication management and administration",
//           "Meal preparation and feeding assistance",
//           "Mobility support and transfer assistance",
//           "Companionship and emotional support",
//           "Light housekeeping and errands",
//           "Monitoring of health and well-being",
//           "Support in everyday life",
//           "Conversations, closeness and safety",
//         ],
//         images: [respite_care_man_img, respite_care_woman_img],
//       },
//       {
//         id: 6,
//         title: "Other leistungen",
//         icon: TrendingUpDownIcon,
//         url: "/leistungen/other-leistungen",
//         slug: "other-leistungen",
//         description: [
//           "In addition to the core leistungen we offer, we also provide a range of other leistungen to meet the diverse needs of our clients. These leistungen are designed to enhance the quality of life and provide additional support beyond basic and medical care. Our other leistungen include:",
//         ],
//         serviceList: [
//           "Walks",
//           "Support in organizing daily life at home",
//           "Transportation leistungen for medical appointments, hairdresser and other errands",
//           "Companionship and social engagement activities",
//           "Assistance with technology and communication devices",
//           "Support for managing finances and paperwork",
//           "Assistance with applying for nursing care benefits and social security",
//           "Assistance with applying for care aids and organizing assistive devices",
//           "Assistance with applying for a care level assessment",
//           "Support during the care level assessment by the Medical Service of the Health Insurance Funds (MDK)",
//           "Measures for cognitive activation, memory-enhancing exercises",
//           "Specialized care for individuals with specific conditions (e.g., dementia care, palliative care)",
//           "Leisure activities (theater, cinema, concert)",
//           "Support for developing and maintaining a daily routine",
//           "Pet care assistance",
//           "Gardening and outdoor maintenance support",
//         ],
//         images: [other_services_img_1, other_services_img_2],
//       },
//     ],
//   },
// };

const data = {
  contactInfo: {
    phone: "+49 89 520 74219",
    fax: "+49 89 327 63110",
    mobile: "+49 178 531 4998",
    email: "info@semi-care.de",
    address: "Jollystraße 5, 81545 München",
  },
  services: {
    id: 1,
    label: "Unsere Leistungen im einzelnen",
    title: "Pflege zu Hause – weil es zu Hause am schönsten ist",
    description: [
      "SemiCare verfolgt ein besonderes Konzept: Wir bieten wie jeder andere Pflegedienst professionelle Leistungen an, die von der Krankenkasse getragen werden.",
      "Darüber hinaus ist es aber auch nach Wunsch möglich, medizinische und nicht-medizinische Leistungen zu buchen, die nicht erstattungsfähig sind.",
      "Der Vorteil: Sie können die für Sie erforderliche Hilfe kompakt und passgenau organisieren, ohne eine Vielzahl von Helfern finden zu müssen.",
      "Welche Leistungen von der Krankenkasse übernommen werden, welche Leistungen Sie selbst bezahlen müssen und was das kostet, klären wir vor Vertragsabschluss in einem unverbindlichen Beratungsgespräch.",
    ],

    services: [
      {
        id: 1,
        title: "Durchführung der Peritonealdialyse (CAPD)",
        icon: Cross,
        url: "/leistungen/peritonealdialyse-(CAPD)",
        slug: "peritonealdialyse-(CAPD)",
        description: [
          "Die Peritonealdialyse (Bauchfelldialyse) ist ein Nierenersatzverfahren, das bei chronischem Nierenversagen Giftstoffe und überschüssiges Wasser aus dem Blut entfernt. Im Gegensatz zur Hämodialyse geschieht dies im Körperinneren unter Nutzung des körpereigenen Bauchfells (Peritoneum) als Filter.",
          'Über einen dauerhaft in den Bauchraum eingesetzten Katheter wird eine spezielle Dialyselösung eingeleitet. Das Bauchfell fungiert als „halbdurchlässige" Membran, durch die Abfallstoffe aus dem Blut in die Lösung übergehen.',
          "Eine Peritonealdialyse verändert den Alltag – für Betroffene genauso wie für ihre Angehörigen. Sie bringt viele Fragen, Unsicherheiten und auch Ängste mit sich. Bei SemiCare lassen wir Sie damit nicht allein. Wir begleiten Menschen mit Peritonealdialyse kompetent, einfühlsam und zuverlässig – direkt bei Ihnen zu Hause. Wir erklären verständlich jeden Schritt, sodass Sie sich sicher fühlen können.",
          "Unsere Leistungen sind folgende:",
        ],
        serviceList: [
          "Fachgerechte Unterstützung bei der Peritonealdialyse (CAPD) im häuslichen Umfeld",
          "Durchführung und Begleitung von CAPD und APD (Cycler) nach ärztlicher Anordnung",
          "Exit-Verbandswechsel",
          "Hilfe bei der Bestellung von Materialien (Baxter oder Fresenius)",
          "Strikte Einhaltung hygienischer Standards zur Infektionsprävention",
          "Vorbereitung, Anschluss und Abschluss der Dialyse",
          "Kontrolle der Ein - und Auslaufmenge",
          "Beobachtung und Dokumentation des Allgemeinzustands",
          "Frühzeitiges Erkennen und Weiterleiten von Auffälligkeiten",
          "Anleitung und Unterstützung von Patienten und Angehörigen",
          "Eine enge Zusammenarbeit mit Ärzten und Dialysezentren",
          "Entlastung der Angehörigen durch zuverlässige, geschulte und strukturierte Pflege",
        ],
        images: [peritoneal_dialysis_img_1, peritoneal_dialysis_img_2],
      },

      {
        id: 2,
        title: "Grundpflege",
        icon: Orbit,
        url: "/leistungen/grundpflege",
        slug: "grundpflege",
        description: [
          "Grundpflege ist besonders wichtig, um Infektionen zu vermeiden. Die Grundpflege unterstützt Menschen bei ihren täglichen Bedürfnissen und sorgt für Wohlbefinden, Hygiene und Sicherheit.",
          "Ziel der Grundpflege ist es, die Selbständigkeit so weit wie möglich zu erhalten, die Gesundheit zu fördern und dem Menschen ein würdevolles Leben zu ermöglichen.",
          "Unser Team bietet folgende Grundpflege an:",
        ],
        serviceList: [
          "Duschen, Baden, Waschen",
          "Hilfe beim An - und Auskleiden",
          "Kochen, mundgerechte Vorbereitung von Speisen",
          "Hilfe bei der Nahrungsaufnahme",
          "Verabreichung von Sondennahrung und Trinknahrung",
          "Unterstützung beim Toilettengang",
          "Verwendung von Inkontinenzprodukten",
          "Reinigung von Harnröhrenkatheter, Wechsel des Katheterbeutels",
          "Reinigung und Versorgung von künstlichen Ausgängen",
          "Pflegerische Maßnahmen zur Vorbeugung von Kontrakturen, Lungenentzündung, Pilzbefall im Mund (Soor), Dekubitus, Thrombose und Verstopfung",
          "Lagerung mit Lagerungshilfsmitteln",
          "Unterstützung beim Gehen",
          "Transfer z.B. vom Bett in den Rollstuhl",
          "Aktivierende Pflege mit Bewegungsübungen",
        ],
        images: [basic_care_img],
      },
      {
        id: 3,
        title: "Behandlungspflege",
        icon: Syringe,
        url: "/leistungen/behandlungspflege",
        slug: "behandlungspflege",
        description: [
          "Die Behandlungspflege umfasst medizinische Maßnahmen, die von Pflegefachkräften auf ärztliche Anordnung im häuslichen Umfeld durchgeführt werden, um Krankheiten zu heilen, zu lindern oder deren Verschlechterung zu verhindern. ",
          "Sie gehört zur häuslichen Krankenpflege (SGB V) und wird von der Krankenkasse bezahlt, unabhängig von der Einstufung des Pflegegrads.",
          "Dazu gehören alle Tätigkeiten, die auf ärztliche Verordnung hin von Pflegekräften aus der Gesundheits– und Altenpflege durchgeführt werden sollen wie z.B.",
        ],
        serviceList: [
          "Verabreichen von Injektionen (z.B. Insulin oder Thromboseprophylaxe)",
          "Wundversorgung und Verbandswechsel",
          "Stellung von Medikamenten und Vorbereitung der Medikamentengabe",
          "Dekubitus Behandlung",
          "Messung von Vitalwerten, Blutzucker sowie Gewichtskontrolle",
          "An- und Ausziehen von Kompressionsstrümpfen, Anlegen von Kompressionsverbänden",
          "Stomaversorgung",
        ],
        images: [treatment_care_img],
      },
      {
        id: 4,
        title: "Zusätzlich buchbare häusliche Betreuungsleistungen",
        icon: BrushCleaning,
        url: "/leistungen/hauswirtschaftliche-leistungen",
        slug: "hauswirtschaftliche-leistungen",
        description: [
          "Unterstützung und sonstige Hilfen im häuslichen Umfeld der pflegedürftigen Person oder seiner Familie in Form von Begleitung, Beschäftigung oder Beaufsichtigung",
          "Wie z.B.",
        ],
        serviceList: [
          "Spaziergänge",
          "Unterstützung bei der Gestaltung des häuslichen Alltags",
          "Freizeitgestaltung (Theater, Kino, Konzert)",
          "Hilfen zur Entwicklung und Aufrechterhaltung einer Tagesstruktur",
          "Maßnahmen zur kognitiven Aktivierung, Übungen der Gedächtnisförderung",
          "Alltagsbegleitung (z.B. Begleitung zum Arzt, Friseur)",
        ],
        images: [domestic_care_img, other_services_img_1],
      },
      {
        id: 5,
        title: "Hauswirtschaftliche Versorgung",
        icon: HandHeart,
        url: "/leistungen/verhinderungspflege",
        slug: "verhinderungspflege",
        description: [
          "Zusätzlich bieten wir verschiedene Zusatzleistungen an, die nicht Teil der Grundpflege und Behandlungspflege sind. ",
          "Bei Bedarf können unsere Patienten Leistungen zur hauswirtschaftlichen Versorgung buchen, die den Ablauf des täglichen Lebens erleichtern. ",
          "Diese werden entweder als Pflegesachleistung über die Pflegekasse oder als Privatleistung abgerechnet.",
        ],
        serviceList: [
          "Einkaufen oder Erledigung von Besorgungen",
          "Putzen und Reinigen der Wohnung",
          "Mahlzeiten vorbereiten",
          "Geschirrspülen",
          "Wäsche waschen, trocknen und bügeln",
        ],
        images: [respite_care_man_img, respite_care_woman_img],
      },
      {
        id: 6,
        title: "Verhinderungspflege",
        icon: TrendingUpDownIcon,
        url: "/leistungen/weitere-leistungen",
        slug: "weitere-leistungen",
        description: [
          "Sie möchten in dem Urlaub fahren. Sie sind krank oder einfach am Ende Ihrer Kräfte. Doch da ist dieser eine Mensch, den Sie jeden Tag liebevoll pflegen. Und Sie fragen sich: Wer kümmert sich um ihm, wenn ich es gerade nicht kann? Genau für diese Momente gibt es die Verhinderungspflege.",
          "Pflege ist Liebe, Verantwortung und oft auch körperliche und seelische Belastung. Sie leisten Großartiges – jeden Tag. Wenn sie verreisen möchten, sich erholen müssen oder selbst krank sind, übernehmen wir in dieser Zeit die Betreuung Ihres Angehörigen – zuverlässig, respektvoll und mit Herz.",
          "Sie dürfen loslassen – ohne schlechtes Gewissen.",
          "Unsere Pflegekräfte helfen bei allem, was gebraucht wird:",
        ],
        serviceList: [
          "Aufstehen, waschen und Anziehen",
          "Essen, Trinken und Medikamente",
          "Begleitung im Alltag",
          "Gespräche, Nähe und Sicherheit",
        ],
        images: [other_services_img_1, other_services_img_2],
      },
    ],
  },
  otherServices: {
    id: 1,
    heading: "Sonstige Leistungen",
    description: [
      "Hilfe bei der Beantragung von Leistungen für die Krankenpflege und Sozialversicherung",
      "Hilfe bei der Beantragung von Pflegehilfsmitteln und Organisation von Hilfsmitteln",
      "Hilfe bei der Beantragung eines Pflegegrads",
      "Begleitung bei der Pflegegradeinstufung durch den MDK",
    ],
  },
};

export default data;
